global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus-products-ms
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus-products-ms:9090
- job_name: app-products-ms
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - localhost:8080
