version: '3'

services:
  redis-products-ms:
    image: redis
    container_name: redis-products-ms
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - cache

  prometheus-products-ms:
    image: prom/prometheus:latest
    container_name: prometheus-products-ms
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    user: root

  grafana-products-ms:
    image: grafana/grafana
    container_name: grafana-products-ms
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monit
    depends_on:
      - prometheus-products-ms
    user: root
